# This will run on Travis' 'new' container-based infrastructure
sudo: false
language: csharp

# Blacklist
branches:
  except:
    - gh-pages

install:
  - nuget install docfx.console -Version 2.31.0 -OutputDirectory .

script:
  - ls docfx.console.2.31.0/tools
  - mono docfx.console.2.31.0/tools/docfx.exe docs/docfx.json
  - echo "" > docs/_site/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  repo: HouraiTeahouse/FantasyCrescendo-Docs
  local-dir: docs/_site
  target-branch: master
  github_token: $GITHUB_TOKEN
  on:
    all_branches: true
 
notifications:
  webhooks:
    urls:
      - https://skyhook.glitch.me/api/webhooks/323190260718764032/3Bl47Pbb0yM1ZTlZwHV0zNPl1yfBaYhLiwYqVzQZWlQDLPMakH3eXdR5NkxSMhqmN2Qu/travis
  on_success: change
  on_failure: always
  on_start: change
  on_cancel: always
  on_error: always
